oSearchData = {
"Введение":  [ ["into.html","Введение",1] ] ,
"Метод":  [ ["into.html","Введение",1] ] ,
"морено":  [ ["into.html","Введение",1] ] ,
"всё":  [ ["sociogram_plain.html","Структура социграммы",1] , ["into.html","Введение",1] ] ,
"все":  [ ["into.html","Введение",2] ] ,
"copyright":  [ ["sociogram_plain.html","Структура социграммы",1] , ["sociogram.html","Социограмма",1] , ["sociomatrix.html","Социоматрица",1] , ["conclution.html","Составление заключени",1] , ["sociogram_filters.html","Работа с фильтрами",1] , ["sociogram_basic.html","Базовы социограммы",1] , ["analytics.html","Обработка данных",1] , ["research.html","Социометрическое исследование",1] , ["developers.html","Разработчики",1] , ["into.html","Введение",1] , ["data_input.html","Ввод данных",1] , ["run_poll.html","Проведение опроса",1] , ["prepare_to_poll.html","Подготовка опроса",1] ] ,
"2009":  [ ["sociogram_plain.html","Структура социграммы",1] , ["sociogram.html","Социограмма",1] , ["sociomatrix.html","Социоматрица",1] , ["conclution.html","Составление заключени",1] , ["sociogram_filters.html","Работа с фильтрами",1] , ["sociogram_basic.html","Базовы социограммы",1] , ["analytics.html","Обработка данных",1] , ["research.html","Социометрическое исследование",1] , ["developers.html","Разработчики",1] , ["into.html","Введение",1] , ["data_input.html","Ввод данных",1] , ["run_poll.html","Проведение опроса",1] , ["prepare_to_poll.html","Подготовка опроса",1] ] ,
"dmitry":  [ ["sociogram_plain.html","Структура социграммы",1] , ["sociogram.html","Социограмма",1] , ["sociomatrix.html","Социоматрица",1] , ["conclution.html","Составление заключени",1] , ["sociogram_filters.html","Работа с фильтрами",1] , ["sociogram_basic.html","Базовы социограммы",1] , ["analytics.html","Обработка данных",1] , ["research.html","Социометрическое исследование",1] , ["developers.html","Разработчики",1] , ["into.html","Введение",1] , ["data_input.html","Ввод данных",1] , ["run_poll.html","Проведение опроса",1] , ["prepare_to_poll.html","Подготовка опроса",1] ] ,
"mamonov":  [ ["sociogram_plain.html","Структура социграммы",1] , ["sociogram.html","Социограмма",1] , ["sociomatrix.html","Социоматрица",1] , ["conclution.html","Составление заключени",1] , ["sociogram_filters.html","Работа с фильтрами",1] , ["sociogram_basic.html","Базовы социограммы",1] , ["analytics.html","Обработка данных",1] , ["research.html","Социометрическое исследование",1] , ["developers.html","Разработчики",1] , ["into.html","Введение",1] , ["data_input.html","Ввод данных",1] , ["run_poll.html","Проведение опроса",1] , ["prepare_to_poll.html","Подготовка опроса",1] ] ,
"ekaterina":  [ ["sociogram_plain.html","Структура социграммы",1] , ["sociogram.html","Социограмма",1] , ["sociomatrix.html","Социоматрица",1] , ["conclution.html","Составление заключени",1] , ["sociogram_filters.html","Работа с фильтрами",1] , ["sociogram_basic.html","Базовы социограммы",1] , ["analytics.html","Обработка данных",1] , ["research.html","Социометрическое исследование",1] , ["developers.html","Разработчики",1] , ["into.html","Введение",1] , ["data_input.html","Ввод данных",1] , ["run_poll.html","Проведение опроса",1] , ["prepare_to_poll.html","Подготовка опроса",1] ] ,
"laktionova":  [ ["sociogram_plain.html","Структура социграммы",1] , ["sociogram.html","Социограмма",1] , ["sociomatrix.html","Социоматрица",1] , ["conclution.html","Составление заключени",1] , ["sociogram_filters.html","Работа с фильтрами",1] , ["sociogram_basic.html","Базовы социограммы",1] , ["analytics.html","Обработка данных",1] , ["research.html","Социометрическое исследование",1] , ["developers.html","Разработчики",1] , ["into.html","Введение",1] , ["data_input.html","Ввод данных",1] , ["run_poll.html","Проведение опроса",1] , ["prepare_to_poll.html","Подготовка опроса",1] ] ,
"created":  [ ["sociogram_plain.html","Структура социграммы",1] , ["sociogram.html","Социограмма",1] , ["sociomatrix.html","Социоматрица",1] , ["conclution.html","Составление заключени",1] , ["sociogram_filters.html","Работа с фильтрами",1] , ["sociogram_basic.html","Базовы социограммы",1] , ["analytics.html","Обработка данных",1] , ["research.html","Социометрическое исследование",1] , ["developers.html","Разработчики",1] , ["into.html","Введение",1] , ["data_input.html","Ввод данных",1] , ["run_poll.html","Проведение опроса",1] , ["prepare_to_poll.html","Подготовка опроса",1] ] ,
"with":  [ ["sociogram_plain.html","Структура социграммы",1] , ["sociogram.html","Социограмма",1] , ["sociomatrix.html","Социоматрица",1] , ["conclution.html","Составление заключени",1] , ["sociogram_filters.html","Работа с фильтрами",1] , ["sociogram_basic.html","Базовы социограммы",1] , ["analytics.html","Обработка данных",1] , ["research.html","Социометрическое исследование",1] , ["developers.html","Разработчики",1] , ["into.html","Введение",1] , ["data_input.html","Ввод данных",1] , ["run_poll.html","Проведение опроса",1] , ["prepare_to_poll.html","Подготовка опроса",1] ] ,
"the":  [ ["sociogram_plain.html","Структура социграммы",1] , ["sociogram.html","Социограмма",1] , ["sociomatrix.html","Социоматрица",1] , ["conclution.html","Составление заключени",1] , ["sociogram_filters.html","Работа с фильтрами",1] , ["sociogram_basic.html","Базовы социограммы",1] , ["analytics.html","Обработка данных",1] , ["research.html","Социометрическое исследование",1] , ["developers.html","Разработчики",1] , ["into.html","Введение",1] , ["data_input.html","Ввод данных",1] , ["run_poll.html","Проведение опроса",1] , ["prepare_to_poll.html","Подготовка опроса",1] ] ,
"freeware":  [ ["sociogram_plain.html","Структура социграммы",1] , ["sociogram.html","Социограмма",1] , ["sociomatrix.html","Социоматрица",1] , ["conclution.html","Составление заключени",1] , ["sociogram_filters.html","Работа с фильтрами",1] , ["sociogram_basic.html","Базовы социограммы",1] , ["analytics.html","Обработка данных",1] , ["research.html","Социометрическое исследование",1] , ["developers.html","Разработчики",1] , ["into.html","Введение",1] , ["data_input.html","Ввод данных",1] , ["run_poll.html","Проведение опроса",1] , ["prepare_to_poll.html","Подготовка опроса",1] ] ,
"edition":  [ ["sociogram_plain.html","Структура социграммы",1] , ["sociogram.html","Социограмма",1] , ["sociomatrix.html","Социоматрица",1] , ["conclution.html","Составление заключени",1] , ["sociogram_filters.html","Работа с фильтрами",1] , ["sociogram_basic.html","Базовы социограммы",1] , ["analytics.html","Обработка данных",1] , ["research.html","Социометрическое исследование",1] , ["developers.html","Разработчики",1] , ["into.html","Введение",1] , ["data_input.html","Ввод данных",1] , ["run_poll.html","Проведение опроса",1] , ["prepare_to_poll.html","Подготовка опроса",1] ] ,
"helpndoc":  [ ["sociogram_plain.html","Структура социграммы",1] , ["sociogram.html","Социограмма",1] , ["sociomatrix.html","Социоматрица",1] , ["conclution.html","Составление заключени",1] , ["sociogram_filters.html","Работа с фильтрами",1] , ["sociogram_basic.html","Базовы социограммы",1] , ["analytics.html","Обработка данных",1] , ["research.html","Социометрическое исследование",1] , ["developers.html","Разработчики",1] , ["into.html","Введение",1] , ["data_input.html","Ввод данных",1] , ["run_poll.html","Проведение опроса",1] , ["prepare_to_poll.html","Подготовка опроса",1] ] ,
"easily":  [ ["sociomatrix.html","Социоматрица",1] , ["sociogram_basic.html","Базовы социограммы",1] , ["data_input.html","Ввод данных",1] , ["into.html","Введение",1] , ["developers.html","Разработчики",1] ] ,
"create":  [ ["data_input.html","Ввод данных",1] , ["sociomatrix.html","Социоматрица",1] , ["sociogram_basic.html","Базовы социограммы",1] , ["into.html","Введение",1] , ["developers.html","Разработчики",1] , ["run_poll.html","Проведение опроса",1] ] ,
"help":  [ ["run_poll.html","Проведение опроса",2] , ["sociomatrix.html","Социоматрица",1] , ["sociogram_plain.html","Структура социграммы",1] , ["sociogram_filters.html","Работа с фильтрами",1] , ["sociogram_basic.html","Базовы социограммы",1] , ["analytics.html","Обработка данных",1] , ["developers.html","Разработчики",1] , ["into.html","Введение",1] , ["data_input.html","Ввод данных",1] , ["research.html","Социометрическое исследование",1] ] ,
"documents":  [ ["sociomatrix.html","Социоматрица",1] , ["sociogram_basic.html","Базовы социограммы",1] , ["data_input.html","Ввод данных",1] , ["into.html","Введение",1] , ["developers.html","Разработчики",1] ] ,
"Разработчики":  [ ["developers.html","Разработчики",2] ] ,
"славные":  [ ["developers.html","Разработчики",1] ] ,
"Социометрическое":  [ ["research.html","Социометрическое исследование",1] ] ,
"исследование":  [ ["research.html","Социометрическое исследование",2] ] ,
"Социметрическое":  [ ["research.html","Социометрическое исследование",1] ] ,
"строится":  [ ["research.html","Социометрическое исследование",1] ] ,
"free":  [ ["sociogram_filters.html","Работа с фильтрами",1] , ["sociogram_plain.html","Структура социграммы",1] , ["research.html","Социометрическое исследование",1] ] ,
"authoring":  [ ["sociogram_plain.html","Структура социграммы",1] , ["research.html","Социометрическое исследование",1] ] ,
"environment":  [ ["sociogram_plain.html","Структура социграммы",1] , ["research.html","Социометрическое исследование",1] ] ,
"Подготовка":  [ ["prepare_to_poll.html","Подготовка опроса",1] ] ,
"опроса":  [ ["prepare_to_poll.html","Подготовка опроса",2] , ["conclution.html","Составление заключени",1] , ["data_input.html","Ввод данных",1] , ["run_poll.html","Проведение опроса",1] ] ,
"При":  [ ["run_poll.html","Проведение опроса",1] , ["prepare_to_poll.html","Подготовка опроса",1] ] ,
"подготовке":  [ ["prepare_to_poll.html","Подготовка опроса",1] ] ,
"следует":  [ ["prepare_to_poll.html","Подготовка опроса",1] ] ,
"full":  [ ["sociogram.html","Социограмма",1] , ["conclution.html","Составление заключени",1] , ["prepare_to_poll.html","Подготовка опроса",1] , ["analytics.html","Обработка данных",1] ] ,
"featured":  [ ["sociogram.html","Социограмма",1] , ["conclution.html","Составление заключени",1] , ["prepare_to_poll.html","Подготовка опроса",1] , ["analytics.html","Обработка данных",1] ] ,
"documentation":  [ ["sociogram_filters.html","Работа с фильтрами",1] , ["conclution.html","Составление заключени",1] , ["prepare_to_poll.html","Подготовка опроса",1] , ["sociogram.html","Социограмма",1] ] ,
"generator":  [ ["sociogram_filters.html","Работа с фильтрами",1] , ["conclution.html","Составление заключени",1] , ["sociogram.html","Социограмма",1] , ["prepare_to_poll.html","Подготовка опроса",1] , ["analytics.html","Обработка данных",1] ] ,
"Проведение":  [ ["run_poll.html","Проведение опроса",1] ] ,
"вроведении":  [ ["run_poll.html","Проведение опроса",1] ] ,
"вопросо":  [ ["run_poll.html","Проведение опроса",1] ] ,
"важно":  [ ["run_poll.html","Проведение опроса",1] ] ,
"соблюсти":  [ ["run_poll.html","Проведение опроса",1] ] ,
"ряд":  [ ["sociogram_basic.html","Базовы социограммы",1] , ["run_poll.html","Проведение опроса",1] ] ,
"условий":  [ ["run_poll.html","Проведение опроса",1] ] ,
"easy":  [ ["run_poll.html","Проведение опроса",1] ] ,
"use":  [ ["run_poll.html","Проведение опроса",1] ] ,
"tool":  [ ["run_poll.html","Проведение опроса",1] ] ,
"html":  [ ["run_poll.html","Проведение опроса",1] ] ,
"files":  [ ["run_poll.html","Проведение опроса",1] ] ,
"and":  [ ["run_poll.html","Проведение опроса",1] ] ,
"web":  [ ["run_poll.html","Проведение опроса",1] ] ,
"sites":  [ ["run_poll.html","Проведение опроса",1] ] ,
"Ввод":  [ ["data_input.html","Ввод данных",2] ] ,
"данных":  [ ["analytics.html","Обработка данных",2] , ["data_input.html","Ввод данных",1] ] ,
"программу":  [ ["data_input.html","Ввод данных",1] ] ,
"результатов":  [ ["conclution.html","Составление заключени",1] , ["data_input.html","Ввод данных",1] ] ,
"действительно":  [ ["data_input.html","Ввод данных",1] ] ,
"очень":  [ ["data_input.html","Ввод данных",1] ] ,
"прост":  [ ["data_input.html","Ввод данных",1] ] ,
"для":  [ ["sociogram_basic.html","Базовы социограммы",1] , ["data_input.html","Ввод данных",1] ] ,
"этого":  [ ["data_input.html","Ввод данных",1] ] ,
"достаточно":  [ ["data_input.html","Ввод данных",1] ] ,
"pdf":  [ ["data_input.html","Ввод данных",1] ] ,
"Обработка":  [ ["analytics.html","Обработка данных",2] ] ,
"это":  [ ["analytics.html","Обработка данных",1] ] ,
"вам":  [ ["analytics.html","Обработка данных",1] ] ,
"тяп":  [ ["analytics.html","Обработка данных",1] ] ,
"ляп":  [ ["analytics.html","Обработка данных",1] ] ,
"Работа":  [ ["sociogram_filters.html","Работа с фильтрами",1] , ["sociomatrix.html","Социоматрица",1] ] ,
"социоматрицей":  [ ["sociomatrix.html","Социоматрица",1] ] ,
"Огого":  [ ["sociomatrix.html","Социоматрица",1] ] ,
"социоматрица":  [ ["sociomatrix.html","Социоматрица",1] ] ,
"chm":  [ ["sociogram_filters.html","Работа с фильтрами",1] , ["sociomatrix.html","Социоматрица",1] ] ,
"Социограмма":  [ ["sociogram.html","Социограмма",2] , ["sociogram_plain.html","Структура социграммы",1] ] ,
"так":  [ ["sociogram.html","Социограмма",1] ] ,
"Простая":  [ ["sociogram_plain.html","Структура социграммы",1] ] ,
"Узлы":  [ ["sociogram_plain.html","Структура социграммы",1] ] ,
"связи":  [ ["sociogram_plain.html","Структура социграммы",1] ] ,
"такие":  [ ["sociogram_plain.html","Структура социграммы",1] ] ,
"вот":  [ ["sociogram_plain.html","Структура социграммы",1] ] ,
"чего":  [ ["sociogram_plain.html","Структура социграммы",1] ] ,
"Базовы":  [ ["sociogram_basic.html","Базовы социограммы",1] ] ,
"социограммы":  [ ["sociogram_filters.html","Работа с фильтрами",1] , ["sociogram_basic.html","Базовы социограммы",1] ] ,
"приложение":  [ ["sociogram_basic.html","Базовы социограммы",1] ] ,
"встроен":  [ ["sociogram_basic.html","Базовы социограммы",1] ] ,
"фильтров":  [ ["sociogram_basic.html","Базовы социограммы",1] ] ,
"построения":  [ ["sociogram_basic.html","Базовы социограммы",1] ] ,
"стандартных":  [ ["sociogram_basic.html","Базовы социограммы",1] ] ,
"социограмм":  [ ["sociogram_basic.html","Базовы социограммы",1] ] ,
"таких":  [ ["sociogram_basic.html","Базовы социограммы",1] ] ,
"как":  [ ["sociogram_basic.html","Базовы социограммы",1] ] ,
"фильтрами":  [ ["sociogram_filters.html","Работа с фильтрами",1] ] ,
"Вид":  [ ["sociogram_filters.html","Работа с фильтрами",1] ] ,
"каждой":  [ ["sociogram_filters.html","Работа с фильтрами",1] ] ,
"полностью":  [ ["sociogram_filters.html","Работа с фильтрами",1] ] ,
"настраиваемый":  [ ["sociogram_filters.html","Работа с фильтрами",1] ] ,
"можете":  [ ["sociogram_filters.html","Работа с фильтрами",1] ] ,
"Составление":  [ ["conclution.html","Составление заключени",1] ] ,
"заключени":  [ ["conclution.html","Составление заключени",1] ] ,
"результате":  [ ["conclution.html","Составление заключени",1] ] ,
"анализа":  [ ["conclution.html","Составление заключени",1] ]
}